/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prodavnicafilmovaapplication;

/**
 *
 * @author Korisnik
 */
public class Dobavljac1 extends javax.swing.JFrame {
MySQL sql;
    /**
     * Creates new form Dobavljac1
     */
    public Dobavljac1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PrikaziDobavljac_B = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        idDobavljaca_TF = new javax.swing.JTextField();
        nazivDobavljaca_TF = new javax.swing.JTextField();
        UnesiDobavljac_B = new javax.swing.JButton();
        ObrisiDobavljac_B = new javax.swing.JButton();
        NazadDobavljac_B = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_Dobavljac = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        adresa_TF = new javax.swing.JTextField();
        email_TF = new javax.swing.JTextField();
        konekcija_IF = new javax.swing.JInternalFrame();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        server_TF = new javax.swing.JTextField();
        korisnickoIme_TF = new javax.swing.JTextField();
        baza_TF = new javax.swing.JTextField();
        Konekcija_B = new javax.swing.JButton();
        lozinka_TF = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PrikaziDobavljac_B.setText("Prikazi Podatke Dobavljac");
        PrikaziDobavljac_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrikaziDobavljac_BActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel1.setText("DOBAVLJAC");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("idDobavljaca");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("nazivDobavljaca");

        nazivDobavljaca_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nazivDobavljaca_TFActionPerformed(evt);
            }
        });

        UnesiDobavljac_B.setText("Unesi Dobavljac");
        UnesiDobavljac_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UnesiDobavljac_BActionPerformed(evt);
            }
        });

        ObrisiDobavljac_B.setText("Obrisi Dobavljac");
        ObrisiDobavljac_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObrisiDobavljac_BActionPerformed(evt);
            }
        });

        NazadDobavljac_B.setText("Nazad");
        NazadDobavljac_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NazadDobavljac_BActionPerformed(evt);
            }
        });

        table_Dobavljac.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        table_Dobavljac.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                table_DobavljacKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(table_Dobavljac);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("adresa");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("email");

        konekcija_IF.setVisible(true);
        konekcija_IF.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                konekcija_IFInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        konekcija_IF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                konekcija_IFMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Server:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Korisničko ime:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Lozinka:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Baza podataka:");

        server_TF.setText(" ");

        korisnickoIme_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                korisnickoIme_TFActionPerformed(evt);
            }
        });

        Konekcija_B.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Konekcija_B.setText("Konektuj se");
        Konekcija_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Konekcija_BActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("KONEKCIJA");
        konekcija_IF.setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout konekcija_IFLayout = new javax.swing.GroupLayout(konekcija_IF.getContentPane());
        konekcija_IF.getContentPane().setLayout(konekcija_IFLayout);
        konekcija_IFLayout.setHorizontalGroup(
            konekcija_IFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(konekcija_IFLayout.createSequentialGroup()
                .addGroup(konekcija_IFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(konekcija_IFLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(konekcija_IFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(129, 129, 129)
                        .addGroup(konekcija_IFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(korisnickoIme_TF)
                            .addComponent(server_TF, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                            .addComponent(baza_TF)
                            .addComponent(lozinka_TF)))
                    .addGroup(konekcija_IFLayout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addGroup(konekcija_IFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addComponent(Konekcija_B))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        konekcija_IFLayout.setVerticalGroup(
            konekcija_IFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(konekcija_IFLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3)
                .addGap(31, 31, 31)
                .addGroup(konekcija_IFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(server_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(konekcija_IFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(korisnickoIme_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(konekcija_IFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lozinka_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(konekcija_IFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(baza_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(Konekcija_B)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(292, 292, 292)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(967, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(idDobavljaca_TF)
                            .addComponent(nazivDobavljaca_TF, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                            .addComponent(adresa_TF)
                            .addComponent(email_TF))
                        .addGap(91, 91, 91))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NazadDobavljac_B, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(UnesiDobavljac_B, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ObrisiDobavljac_B, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PrikaziDobavljac_B, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(konekcija_IF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(idDobavljaca_TF)
                        .addComponent(UnesiDobavljac_B)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ObrisiDobavljac_B)
                    .addComponent(jLabel3)
                    .addComponent(nazivDobavljaca_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(adresa_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(email_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(PrikaziDobavljac_B)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 302, Short.MAX_VALUE)
                .addComponent(NazadDobavljac_B)
                .addGap(42, 42, 42))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(konekcija_IF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nazivDobavljaca_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nazivDobavljaca_TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nazivDobavljaca_TFActionPerformed

    private void NazadDobavljac_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NazadDobavljac_BActionPerformed
        this.setVisible(false);
        KonekcijaGUI1 s=new KonekcijaGUI1();
        s.setVisible(true);
    }//GEN-LAST:event_NazadDobavljac_BActionPerformed

    private void ObrisiDobavljac_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObrisiDobavljac_BActionPerformed
      this.sql.ObrisiDobavljac(String.valueOf(this.table_Dobavljac.getValueAt
                        (this.table_Dobavljac.getSelectedRow(), 0)));
        this.sql.PrikaziPodatkeDobavljac(table_Dobavljac);
    }//GEN-LAST:event_ObrisiDobavljac_BActionPerformed

    private void korisnickoIme_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_korisnickoIme_TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_korisnickoIme_TFActionPerformed

    private void Konekcija_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Konekcija_BActionPerformed
        this.sql=new MySQL();
        this.sql.Konekcija(this.server_TF.getText(),this.korisnickoIme_TF.getText(),
            this.lozinka_TF.getText(),this.baza_TF.getText());
    }//GEN-LAST:event_Konekcija_BActionPerformed

    private void konekcija_IFInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_konekcija_IFInternalFrameClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_konekcija_IFInternalFrameClosing

    private void konekcija_IFMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_konekcija_IFMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_konekcija_IFMouseExited

    private void UnesiDobavljac_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UnesiDobavljac_BActionPerformed
     this.sql.UnesiDobavljac(this.idDobavljaca_TF.getText(), this.nazivDobavljaca_TF.getText(), this.adresa_TF.getText(), this.email_TF.getText());
                
        this.sql.PrikaziPodatkeDobavljac(table_Dobavljac);
    }//GEN-LAST:event_UnesiDobavljac_BActionPerformed

    private void PrikaziDobavljac_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrikaziDobavljac_BActionPerformed
    this.sql.PrikaziPodatkeDobavljac(table_Dobavljac);
    }//GEN-LAST:event_PrikaziDobavljac_BActionPerformed

    private void table_DobavljacKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_table_DobavljacKeyReleased
    if(this.table_Dobavljac.getSelectedColumn()==1){
         this.sql.AzuriranjeDobavljac(String.valueOf(this.table_Dobavljac.getValueAt(this.table_Dobavljac.getSelectedRow(), 0)),
                                String.valueOf(this.table_Dobavljac.getValueAt(this.table_Dobavljac.getSelectedRow(),
                                        this.table_Dobavljac.getSelectedColumn())));
    }//GEN-LAST:event_table_DobavljacKeyReleased
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dobavljac1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dobavljac1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dobavljac1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dobavljac1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dobavljac1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Konekcija_B;
    private javax.swing.JButton NazadDobavljac_B;
    private javax.swing.JButton ObrisiDobavljac_B;
    private javax.swing.JButton PrikaziDobavljac_B;
    private javax.swing.JButton UnesiDobavljac_B;
    private javax.swing.JTextField adresa_TF;
    private javax.swing.JTextField baza_TF;
    private javax.swing.JTextField email_TF;
    private javax.swing.JTextField idDobavljaca_TF;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JInternalFrame konekcija_IF;
    private javax.swing.JTextField korisnickoIme_TF;
    private javax.swing.JTextField lozinka_TF;
    private javax.swing.JTextField nazivDobavljaca_TF;
    private javax.swing.JTextField server_TF;
    private javax.swing.JTable table_Dobavljac;
    // End of variables declaration//GEN-END:variables
}
