/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prodavnicafilmovaapplication;

/**
 *
 * @author Korisnik
 */
public class Racun1 extends javax.swing.JFrame {
MySQL sql;
    /**
     * Creates new form Racun
     */
    public Racun1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PrikaziRacun_B = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ObrisiRacun_B = new javax.swing.JButton();
        NazadRacun_B = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_Racun = new javax.swing.JTable();
        konekcija_IF = new javax.swing.JInternalFrame();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        server_TF = new javax.swing.JTextField();
        korisnickoIme_TF = new javax.swing.JTextField();
        baza_TF = new javax.swing.JTextField();
        Konekcija_B = new javax.swing.JButton();
        lozinka_TF = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PrikaziRacun_B.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PrikaziRacun_B.setText("Prikazi Podatke Racun");
        PrikaziRacun_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrikaziRacun_BActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel1.setText("RACUN");

        ObrisiRacun_B.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ObrisiRacun_B.setText("Obrisi Racun");
        ObrisiRacun_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObrisiRacun_BActionPerformed(evt);
            }
        });

        NazadRacun_B.setText("Nazad");
        NazadRacun_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NazadRacun_BActionPerformed(evt);
            }
        });

        table_Racun.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(table_Racun);

        konekcija_IF.setVisible(true);
        konekcija_IF.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                konekcija_IFInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        konekcija_IF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                konekcija_IFMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Server:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Korisničko ime:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Lozinka:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Baza podataka:");

        server_TF.setText(" ");

        korisnickoIme_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                korisnickoIme_TFActionPerformed(evt);
            }
        });

        Konekcija_B.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Konekcija_B.setText("Konektuj se");
        Konekcija_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Konekcija_BActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("KONEKCIJA");
        konekcija_IF.setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout konekcija_IFLayout = new javax.swing.GroupLayout(konekcija_IF.getContentPane());
        konekcija_IF.getContentPane().setLayout(konekcija_IFLayout);
        konekcija_IFLayout.setHorizontalGroup(
            konekcija_IFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(konekcija_IFLayout.createSequentialGroup()
                .addGroup(konekcija_IFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(konekcija_IFLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(konekcija_IFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(129, 129, 129)
                        .addGroup(konekcija_IFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(korisnickoIme_TF)
                            .addComponent(server_TF, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                            .addComponent(baza_TF)
                            .addComponent(lozinka_TF)))
                    .addGroup(konekcija_IFLayout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addGroup(konekcija_IFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addComponent(Konekcija_B))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        konekcija_IFLayout.setVerticalGroup(
            konekcija_IFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(konekcija_IFLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3)
                .addGap(31, 31, 31)
                .addGroup(konekcija_IFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(server_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(konekcija_IFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(korisnickoIme_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(konekcija_IFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lozinka_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(konekcija_IFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(baza_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(Konekcija_B)
                .addContainerGap(185, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(292, 292, 292)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(941, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(NazadRacun_B, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PrikaziRacun_B, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addComponent(ObrisiRacun_B, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(konekcija_IF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(ObrisiRacun_B)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PrikaziRacun_B)
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(konekcija_IF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(NazadRacun_B)
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NazadRacun_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NazadRacun_BActionPerformed
        this.setVisible(false);
        KonekcijaGUI1 s=new KonekcijaGUI1();
        s.setVisible(true);
    }//GEN-LAST:event_NazadRacun_BActionPerformed

    private void korisnickoIme_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_korisnickoIme_TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_korisnickoIme_TFActionPerformed

    private void Konekcija_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Konekcija_BActionPerformed
        this.sql=new MySQL();
        this.sql.Konekcija(this.server_TF.getText(),this.korisnickoIme_TF.getText(),
            this.lozinka_TF.getText(),this.baza_TF.getText());
    }//GEN-LAST:event_Konekcija_BActionPerformed

    private void konekcija_IFInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_konekcija_IFInternalFrameClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_konekcija_IFInternalFrameClosing

    private void konekcija_IFMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_konekcija_IFMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_konekcija_IFMouseExited

    private void ObrisiRacun_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObrisiRacun_BActionPerformed
     this.sql.ObrisiRacun(String.valueOf(this.table_Racun.getValueAt
                        (this.table_Racun.getSelectedRow(), 0)));
        this.sql.PrikaziPodatkeRacun(table_Racun);
    }//GEN-LAST:event_ObrisiRacun_BActionPerformed

    private void PrikaziRacun_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrikaziRacun_BActionPerformed
       this.sql.PrikaziPodatkeRacun(table_Racun);
    }//GEN-LAST:event_PrikaziRacun_BActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Racun1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Racun1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Racun1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Racun1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Racun1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Konekcija_B;
    private javax.swing.JButton NazadRacun_B;
    private javax.swing.JButton ObrisiRacun_B;
    private javax.swing.JButton PrikaziRacun_B;
    private javax.swing.JTextField baza_TF;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JInternalFrame konekcija_IF;
    private javax.swing.JTextField korisnickoIme_TF;
    private javax.swing.JTextField lozinka_TF;
    private javax.swing.JTextField server_TF;
    private javax.swing.JTable table_Racun;
    // End of variables declaration//GEN-END:variables
}
